// 86. catch block:
// code statement:
// #include <iostream>
// using namespace std;
// int main(){
//     try{
//         int a;
//         int b;
//         cout<<"enter value of a"<<endl;
//         cin>>a;
//         cout<<"enter value of b"<<endl;
//         cin>>b;
//         if(b == 0){
//             throw 404;
//         }
//         int c = a/b;
//         cout<<c;
//     }
//     catch(int num){
//         cout<<"can not divide by 0"<<endl;
//         cout<<"error found";
//     }
//     return 0;
// }